-- liquibase formatted sql

-- changeset abel:1

CREATE SEQUENCE IF NOT EXISTS seal_exp_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE access_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(512)                            NOT NULL,
    token      VARCHAR(512)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_access_token PRIMARY KEY (id)
);

CREATE TABLE beliefs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    description VARCHAR(514),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_beliefs PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    categories TEXT[],
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE goals
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    name        VARCHAR(67),
    description VARCHAR(514),
    start_date  date,
    finish_date date,
    active      BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_goals PRIMARY KEY (id)
);

CREATE TABLE habits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    goal_id    BIGINT,
    name       VARCHAR(67),
    category   VARCHAR(35),
    days_week  SMALLINT,
    active     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_habits PRIMARY KEY (id)
);

CREATE TABLE recovery
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    first_question  VARCHAR(255)                            NOT NULL,
    second_question VARCHAR(255)                            NOT NULL,
    third_question  VARCHAR(255)                            NOT NULL,
    first_response  VARCHAR(256)                            NOT NULL,
    second_response VARCHAR(256)                            NOT NULL,
    third_response  VARCHAR(256)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_recovery PRIMARY KEY (id)
);

CREATE TABLE seal_exp
(
    id         BIGINT  NOT NULL,
    name       VARCHAR(67),
    start_xp   INTEGER NOT NULL,
    finish_xp  INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_seal_exp PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    habit_id   BIGINT,
    name       VARCHAR(256)                            NOT NULL,
    comment    VARCHAR(514),
    finished   BOOLEAN                                 NOT NULL,
    xp_value   INTEGER,
    date       date                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(34),
    last_name   VARCHAR(256),
    birth_date  date,
    gender      SMALLINT,
    username    VARCHAR(256),
    email       VARCHAR(258),
    password    VARCHAR(255),
    mobile      VARCHAR(20),
    experience  INTEGER                                 NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    recovery_id BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE access_token
    ADD CONSTRAINT uc_access_token_token UNIQUE (token);

ALTER TABLE access_token
    ADD CONSTRAINT uc_access_token_username UNIQUE (username);

ALTER TABLE recovery
    ADD CONSTRAINT uc_recovery_user UNIQUE (user_id);

ALTER TABLE seal_exp
    ADD CONSTRAINT uc_seal_exp_finish_xp UNIQUE (finish_xp);

ALTER TABLE seal_exp
    ADD CONSTRAINT uc_seal_exp_start_xp UNIQUE (start_xp);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE beliefs
    ADD CONSTRAINT FK_BELIEFS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE goals
    ADD CONSTRAINT FK_GOALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE habits
    ADD CONSTRAINT FK_HABITS_ON_GOAL FOREIGN KEY (goal_id) REFERENCES goals (id);

ALTER TABLE habits
    ADD CONSTRAINT FK_HABITS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE recovery
    ADD CONSTRAINT FK_RECOVERY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_HABIT FOREIGN KEY (habit_id) REFERENCES habits (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_RECOVERY FOREIGN KEY (recovery_id) REFERENCES recovery (id);